name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_sast:
        description: '跳过 SpotBugs 和 Dependency-Check 分析'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean verify -DskipTests

      # 检查是否跳过 SAST 步骤
      - name: Run SpotBugs Analysis
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        run: mvn spotbugs:check || true

      - name: Upload SpotBugs Report
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugs.xml

      - name: Fail on SpotBugs High Priority Issues
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        run: |
          if grep -q '<BugInstance.*priority="1"' target/spotbugs.xml; then
            echo "High priority issues found by SpotBugs!"
            exit 1
          fi

      - name: Cache OWASP Dependency-Check Data
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check
          key: dependency-check-${{ runner.os }}-${{ hashFiles('**/dependency-check.properties') }}
          restore-keys: |
            dependency-check-${{ runner.os }}-

      - name: Run Dependency Check
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        run: |
          mkdir -p reports
          mvn org.owasp:dependency-check-maven:check -Dformat=ALL -Dout=reports/

      - name: Upload Dependency Check Report
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html

      - name: Fail on High Vulnerabilities
        if: ${{ github.event.inputs.skip_sast != 'true' }}
        run: |
          if grep -q '<severity>Critical</severity>\|<severity>High</severity>' reports/dependency-check-report.xml; then
            echo "High or Critical vulnerabilities found!"
            exit 1
          fi

      # 登录 Docker 并推送镜像
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-backend:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/web-backend:latest
